### ISSUE TITLE
install process

### ISSUE THREAD

**Issue by marcoleder** [Tailslide/BatterySaver#1]
Hey there, how can I install it (Windows 10, 64bit, intel)?

Best, Marco

**Comment by Tailslide** [comment]
This is just the source code.. I'll upload the executable later today.

**Comment by Tailslide** [comment]
I published a release.. click 'Releases Version 1' on the main page or go here:
https://github.com/Tailslide/BatterySaver/releases/tag/V1.0

**Comment by marcoleder** [comment]
thy m8!
